I made a code that works with a JSON file
DmytroPetrikin/1levelV2 pull request #2
Opened 2024-09-09 14:49 UTC by DmytroPetrikin

2024-09-14 13:59 UTC, anton-moroz requested changes

2024-09-14 13:59 UTC, anton-moroz commented on vJson/endPoint/deleteItem.php
> +            $todoItem['id']--;
no sense in reducing id. In further you mostly will work with mysql database. reducing id there will bring you problems

2024-09-14 13:59 UTC, anton-moroz commented on vJson/endPoint/getItems.php
> +    return ['items' => json_decode($jsonFile, true)];
check code styles

2024-09-14 13:59 UTC, anton-moroz commented on vJson/endPoint/changeItem.php
> +            $todo['text'] = $newTodoItem['text'];
where is xss prevention?

2024-11-11 15:04 UTC, anton-moroz requested changes

2024-11-11 15:04 UTC, anton-moroz commented on setup_bd.php
> +if ($conn->query($sql) !== TRUE) {
what will you do if there will be three more queries?
how will you execute them?

2024-11-11 15:04 UTC, anton-moroz commented on authentication/logout.php
> +    $_SESSION = array();
what logic do you put here?
why is this needed?

2024-11-11 15:04 UTC, anton-moroz commented on config.php
> +const ACTIONS = [
this is router things, it shouldn't be here

2024-11-11 15:04 UTC, anton-moroz commented on router.php
> +    $response = match ($_GET[ACTION]) {
you can try `fn($data) => {}`
the code will be a bit shorter.

2024-11-11 15:04 UTC, anton-moroz commented on router.php
> +    $response = match ($_GET[ACTION]) {
but I don't like that you have a lot of repeated code
in each variant you call `require_once` and almost in each case you call `isValueMissing`

2024-11-11 15:04 UTC, anton-moroz commented on authentication/login.php
> +    $userSearchStatement = $bd->prepare("SELECT " . COLUMN_USER_ID . ", " . COLUMN_USER_PASSWORD . " FROM " . TABLE_NAME_FOR_USERS . " WHERE " . COLUMN_USER_LOGIN . " = :login");
don't see xss prevention

2024-11-11 15:04 UTC, anton-moroz commented on vJson/addItem.php
> +    echo json_encode(addItem($data));
you can remove functions and write just code, as the functionality is not reused mostly

2024-11-11 15:04 UTC, anton-moroz commented on authentication/login.php
> +    $userSearchStatement = $bd->prepare("SELECT " . COLUMN_USER_ID . ", " . COLUMN_USER_PASSWORD . " FROM " . TABLE_NAME_FOR_USERS . " WHERE " . COLUMN_USER_LOGIN . " = :login");
in register.php - same

2024-11-11 15:04 UTC, anton-moroz commented on vJson/addItem.php
> +    echo json_encode(addItem($data));
same with other files

2024-11-11 15:04 UTC, anton-moroz commented on vPDO/deleteItem.php
> +        return ['ok' => true];
empty line before

2024-11-11 15:18 UTC, DmytroPetrikin commented on authentication/login.php
> +    $userSearchStatement = $bd->prepare("SELECT " . COLUMN_USER_ID . ", " . COLUMN_USER_PASSWORD . " FROM " . TABLE_NAME_FOR_USERS . " WHERE " . COLUMN_USER_LOGIN . " = :login");
робити і для логіна і для пароля ?

2024-11-11 15:20 UTC, DmytroPetrikin commented on router.php
> +    $response = match ($_GET[ACTION]) {
щодо require_once, я можу зробити 2 файли endPointToDo (в якому будуть 4 функції) і підключати її на початку роутера, те ж саме з логіном і тд. Тобто буде всього 2 файли які я підключу одразу. А щодо isValueMissing там же для кожного випадку перевіряється трохи різне

2024-11-11 15:21 UTC, DmytroPetrikin commented on config.php
> +const ACTIONS = [
Я гадав що всі константи повинні бути в одному файлі з константами

2024-11-11 15:21 UTC, DmytroPetrikin commented on config.php
> +const ACTIONS = [
Чи в такому файлі повинні бути тільки загальні константи ?(тобто ті які використовуються як мінімум в 2 і більше файлах)?

2024-11-11 15:22 UTC, DmytroPetrikin commented on authentication/logout.php
> +    $_SESSION = array();
Логіка в тому що я стираю ід юзера з сессії і мене перекине на сторінку на якій потрібно залогінитись

2024-11-11 15:27 UTC, DmytroPetrikin commented on vJson/addItem.php
> +    echo json_encode(addItem($data));
Не дуже зрозумів :( 
Я більшість функцій використовую один раз, то тепер не потрібно виносити їх в функції ? ну тобто файл який відповідає за додавання ітема не розбивати на зрозумілі функції а писати одним шматком коду ?

2024-11-14 12:51 UTC, anton-moroz commented on authentication/login.php
> +    $userSearchStatement = $bd->prepare("SELECT " . COLUMN_USER_ID . ", " . COLUMN_USER_PASSWORD . " FROM " . TABLE_NAME_FOR_USERS . " WHERE " . COLUMN_USER_LOGIN . " = :login");
for login - yes
for password - make a list of allowed characters and validate for them

2024-11-14 12:51 UTC, anton-moroz commented on authentication/logout.php
> +    $_SESSION = array();
you can do it with `session_destroy()`
what is the purpose of `$_SESSION = array();`?

2024-11-14 12:51 UTC, anton-moroz commented on config.php
> +const ACTIONS = [
make separate config for database, separate for router etc.

2024-11-14 12:51 UTC, anton-moroz commented on router.php
> +    $response = match ($_GET[ACTION]) {
no, keep files structure as it is, it's fine
you can make your code shorter and remove duplicates if you transform it a little bit. What do you do with code that is repeated twice or more times?

2024-11-14 12:51 UTC, anton-moroz commented on vJson/addItem.php
> +    echo json_encode(addItem($data));
you can do both ways, but just don't make things complicated

2024-11-28 13:24 UTC, DmytroPetrikin commented on authentication/logout.php
> +    $_SESSION = array();
прочитав шо сешн_дестрой руйнує сессію але не очишає глобальний масив одразу, тому і використовував. Але спробував без очищення масива і все працює як треба

2024-11-29 14:11 UTC, anton-moroz commented on authentication/logout.php
> +    $_SESSION = array();
Yep, exactly. I was just interested if you have some special logic for that

2024-11-30 12:32 UTC, DmytroPetrikin commented on vPDO/deleteItem.php
> +        return ['ok' => true];
Якщо я правильно прочитав гайд по коду то наче не потрібно вставляти порожній рядок перед ретьорн якщо він написаний першим в батьківському блоку

2024-12-06 09:11 UTC, anton-moroz requested changes

2024-12-06 09:11 UTC, anton-moroz commented on validation.php
> +        throw new Exception("Password must contain at least one special character");
it's better to check if password matches allowed symbols, but not vice versa

2024-12-06 09:11 UTC, anton-moroz commented on setup_bd.php
> +    "CREATE TABLE IF NOT EXISTS `" . TABLE_NAME_FOR_USERS . "` (
it's better not to use constants for table name or column, because in future you might need to rename it and you will have troubles

2024-12-06 09:11 UTC, anton-moroz commented on router.php
> +        LOGIN => loginUser(connectBd(), $data[COLUMN_USER_LOGIN], $data[COLUMN_USER_PASSWORD]),
why don't you just connect and pass connection?

2024-12-06 09:11 UTC, anton-moroz commented on router.php
> +    echo json_encode($response);
it's a bad practice to return errors with 200 code

2024-12-06 09:11 UTC, anton-moroz commented on router.php
> +    echo json_encode($response);
some front-end devs would like to beat you for this :)

2024-12-16 14:54 UTC, anton-moroz requested changes

2024-12-16 14:54 UTC, anton-moroz commented on router.php
> +    echo json_encode($response);
this is still not resolved

2024-12-16 14:54 UTC, anton-moroz commented on vPDO/deleteItem.php
> +        return ['ok' => true];
yep, you are right. I didn't notice that second line is `if`
sorry

2024-12-16 14:54 UTC, anton-moroz commented on validation.php
> +        throw new Exception("Password must contain at least one special character");
what special character?
Which are allowed and which are not?
how can user understand this?

2025-02-03 18:46 UTC, anton-moroz requested changes

2025-02-03 18:46 UTC, anton-moroz commented on router.php
> +    $response = match ($action) {
add empty line before

2025-02-03 18:46 UTC, anton-moroz commented on vPDO/changeItem.php
> +        return ['success' => 'Item updated successfully'];
empty line before

2025-02-24 16:06 UTC, anton-moroz approved these changes

2025-02-24 16:06 UTC, anton-moroz commented on router.php
> +        default => [http_response_code(RESPONSE_CODE_BAD_REQUEST) && 'error' => 'Unknown request']
it will be 404 not found

2025-02-24 16:06 UTC, anton-moroz commented on authentication/logout.php
> +    throw new Exception(true);
what is the point of throwing exception for logout?

2025-02-24 16:06 UTC, anton-moroz commented on router.php
> +        default => [http_response_code(RESPONSE_CODE_BAD_REQUEST) && 'error' => 'Unknown request']
you could do 
```
default => function () {
http_response_code(RESPONSE_CODE_BAD_REQUEST);

return 'error' => 'Unknown request';
}
```

2025-03-04 19:34 UTC, anton-moroz requested changes

2025-03-04 19:34 UTC, anton-moroz commented on authentication/login.php
> +    throw new Exception('Invalid login or password.');
what code will be returned?

2025-03-04 19:34 UTC, anton-moroz commented on authentication/register.php
> +    throw new Exception('Failed to register user');
same, what code will be returned?

2025-03-04 19:34 UTC, anton-moroz commented on router.php
> +    $connect = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USER, DB_PASSWORD);
database connection should be in another file. Also, you are not using `$connect` here, so remove it from router

2025-03-04 19:34 UTC, anton-moroz commented on router.php
> +    $connect = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USER, DB_PASSWORD);
import in files where `$connection` is needed

2025-03-06 16:10 UTC, DmytroPetrikin commented on authentication/login.php
> +    throw new Exception('Invalid login or password.');
if all checks are passed, ['ok'=>true] will be returned, otherwise an exception will be thrown, which is handled by the try/catch construct in router

2025-03-06 16:14 UTC, DmytroPetrikin commented on authentication/register.php
> +    throw new Exception('Failed to register user');
If the user exists, an exception will be thrown , If the password is validated and the registration is successful, an array is returned, If execute() failed to insert the user into the database, an exception is thrown. All exceptions are handled in the router

2025-03-06 16:30 UTC, DmytroPetrikin commented on router.php
> +    $connect = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USER, DB_PASSWORD);
Добре, я винесу $connect  в інший файл і зроблю в ньому метод getDatabaseConnection() який буде повертати PDO. Чи можу я лишити такий запис 
        LOGIN => loginUser(getDatabaseConnection(), $data[COLUMN_USER_LOGIN], $data[COLUMN_USER_PASSWORD])
        чи мені треба напряму в файлі login.php підключати і вже там брати цей connect?

2025-03-10 11:54 UTC, anton-moroz commented on authentication/login.php
> +    throw new Exception('Invalid login or password.');
yep, but what code should be returned in the case if checks are not passed?
and what code is actually returned?

2025-03-10 11:55 UTC, anton-moroz commented on router.php
> +    $connect = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USER, DB_PASSWORD);
краще підключати там, де цей функціонал використовуєш

2025-06-08 17:34 UTC, anton-moroz approved these changes

2025-06-09 08:07 UTC, closed without merging

2025-06-09 08:08 UTC, DmytroPetrikin commented
level 2 TODO